"""add_sellers_user_fk

Revision ID: e7e32d8e1b68
Revises: dd14f5a6de31
Create Date: 2026-03-02 11:41:41.226925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7e32d8e1b68'
down_revision: Union[str, None] = 'dd14f5a6de31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'sellers', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sellers', type_='foreignkey')
    # ### end Alembic commands ###
